route:
  group_by: ['stock_alerts', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'email'
    email_configs:
      - to: 'vijayanantham143@gmail.com'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['stock_alerts', 'dev', 'instance']
