apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-server
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"  # The path where your application exposes metrics.
        prometheus.io/port: "8080"      # The port where your application exposes metrics.
      labels:
        app: stock-server
    spec:
      containers:
      - name: stock-server
        image: containers.cisco.com/vijaysek/stockserver:v2
        ports:
        - containerPort: 8080
