apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-ksvc
spec:
  template:
    spec:
      containers:
        - image: my-app-image
          ports:
            - containerPort: 8080