apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'webex'
      group_by: ['alertname', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
      - name: 'webex'
        webex_configs:
        - api_url: https://webexapis.com/v1/messages
          send_resolved: true
          room_id: "Y2lzY29zcGFyazovL3VzL1JPT00vY2UyMjVlZjAtODc3MC0xMWVlLWEzYjEtZmI3ZmU5MWQ3NmZk"
          http_config:
            tls_config:
              insecure_skip_verify: true
            authorization:
              type: Bearer
              credentials: "YTQwOTQyNTItNWRhMy00YWIwLWI1ZDAtNWE0MGJmOTM4MmY1MGUxNTE1NDYtNjJk_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f"
    templates:
      - /etc/alertmanager/*.tmpl
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: my-prometheus
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-11-15T17:00:50Z"
  labels:
    app.kubernetes.io/instance: my-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.26.0
    helm.sh/chart: alertmanager-1.7.0
  name: my-prometheus-alertmanager
  namespace: default
  resourceVersion: "121707"
  uid: acee6f16-d109-424c-9a2c-5cafb6e7ae8b
